### ISSUE TITLE
Undefined property: stdClass::$_embedded  

### ISSUE THREAD

**Issue by BenWoodford** [leeovery/wordpress-to-laravel#1]
[Edit2] Might as well use this for a real issue now.

This is in PostTransformer.php

It seems the REST API v2 doesn't report back anything called $_embedded relating to the featured image of a post. Am I missing something here?

**Comment by leeovery** [comment]
Hey Ben,

All seems fine for me. Ill check it out.

**Comment by leeovery** [comment]
Ben,

Which API are you using? Seems WP 4.7 now comes with an API, which I havent used (yet).

**Comment by leeovery** [comment]
Try run composer update and use 1.0.6 version. Should fix it. Im guessing theres some setting in wp where the featured image doesnt pull through - or perhaps you don't have a featured image.

Also, Ive just tested with the wp 4.7 api and it works fine. Seems its the same api just pulled in to the core code.

Reopen if that doesnt fix it please. :)

**Comment by BenWoodford** [comment]
I had the plugin installed, as per usual I only glanced over the readme and saw the link, I'm already on 4.7 though so don't need it. Just run the update which has fixed some of it... but it isn't pulling author, category or featured image for any posts (and they do have those).

Looking at the endpoint itself, there's "author"/"author_name" and a featured_media field but nothing regarding an _embedded field. Apparently the _embed $_GET parameter isn't working for some reason.

EDIT: Could be related to [this](https://github.com/WP-API/WP-API/issues/2611) as I'm using nginx.

**Comment by BenWoodford** [comment]
Nipped the issue on the bud, I was missing $try_files in my nginx config.

**Comment by leeovery** [comment]
Ah good find. Glad you sorted it. Would have been going around in circles for a while on that!!
