### ISSUE TITLE
Category not sync after Update Category in Blog

### ISSUE THREAD

**Issue by dreamid27** [leeovery/wordpress-to-laravel#10]
I found the issue , when I try to sync my website with the blog.  that's work like charm. 

butw when i already to edit category name in blog , and run sync command (php artisan wordpress-to-laravel:import). 

note : category name , not the category of post. 

the category not updated. 

i use laravel 5,3 and php ver 5 . 

*sorry for bad english.

**Comment by leeovery** [comment]
New 2.2 release will fix this :)
