### ISSUE TITLE
Custom Post Types & Custom Fields

### ISSUE THREAD

**Issue by ghost** [leeovery/wordpress-to-laravel#11]
Is there a way to handle these?

**Comment by vesper8** [comment]
I've added a pull request to support custom post types:
https://github.com/leeovery/wordpress-to-laravel/pull/14

also feel free to use my fork which supports it https://github.com/vesper8/wordpress-to-laravel

**Comment by leeovery** [comment]
Will try to merge that in tomorrow. It needs some reviewing.

**Comment by leeovery** [comment]
New 2.2 release will fix this :)

**Comment by vesper8** [comment]
awesome!

Wish you had added the 'type' column to the migration and PostTransformer though.. I also added a 'link' column for my own taste.. but I think the type column is especially useful when dealing with multiple custom post types

**Comment by leeovery** [comment]
Could you perhaps do another pull request for the type stuff and I’ll check it out 

Thanks.
