### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by paulrajib** [leeovery/wordpress-to-laravel#12]
composer create-project --prefer-dist laravel/laravel larawpt2
cd larawpt2
raj@raj-K45A:/var/www/html/larawpt2$ composer require leeovery/wordpress-to-laravel
Using version ^2.1 for leeovery/wordpress-to-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for leeovery/wordpress-to-laravel ^2.1 -> satisfiable by leeovery/wordpress-to-laravel[v2.1].
    - Conclusion: remove laravel/framework v5.7.2
    - Conclusion: don't install laravel/framework v5.7.2
    - leeovery/wordpress-to-laravel v2.1 requires illuminate/events 5.6.* -> satisfiable by illuminate/events[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/events 5.6.x-dev|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.0|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.1|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.10|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.11|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.12|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.13|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.14|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.15|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.16|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.17|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.19|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.2|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.20|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.21|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.22|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.23|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.24|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.25|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.26|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.27|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.28|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.29|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.3|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.30|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.31|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.32|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.33|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.34|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.35|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.36|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.37|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.38|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.4|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.5|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.6|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.7|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.8|don't install laravel/framework v5.7.2
    - don't install illuminate/events v5.6.9|don't install laravel/framework v5.7.2
    - Installation request for laravel/framework (locked at v5.7.2, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by vesper8** [comment]
this package hasn't been updated in 10 months hence it's only compatible with Laravel 5.6

you can use my fork https://github.com/vesper8/wordpress-to-laravel

or fork it yourself and make the same modifications as I did here https://github.com/vesper8/wordpress-to-laravel/commit/513c4f2629a0854ddfec7b0636ce25ee92875eae

I also submitted a PR but it may or may not be pulled in

**Comment by leeovery** [comment]
New 2.2 release will fix this :)

**Comment by djurovicigoor** [comment]
Not fixed in v2.2
