### ISSUE TITLE
-F/--force-all doesn't actually exist in the code?

### ISSUE THREAD

**Issue by BenWoodford** [leeovery/wordpress-to-laravel#2]
Finally getting on to sorting a proper import, etc and have noticed that there isn't actually any mention of --force-all in the code? Only page, per-page and truncate exist in Importer.php while --force-all is only mentioned in the signature.

**Comment by leeovery** [comment]
Hey,

Good catch. I have no idea where that went. I reckon I coded that in the package when it was part of my app and forgot to move it across.

Ill check it out now. Could do with a distraction! :)

**Comment by BenWoodford** [comment]
It'll sync existing posts right? So perhaps something that could be run hourly to update and changes to old stuff?

**Comment by leeovery** [comment]
Im implementing the force-all option now. Wont be long.

By default it syncs the first page of results, which is 5 posts by default. Those are ordered by the modified date, so itll pick up recent changes. So you could edit a post a year old, and the importer should pick that up and sync it.

I run the importer every minute using the laravel scheduler, as per the readme.

**Comment by BenWoodford** [comment]
Ah got'cha, modified date not published date, yeah.

**Comment by leeovery** [comment]
Ok. The force-all option is implemented now, along with a few other minor improvements. Took a little longer than expected.

Let me know if you run into any other issues.
