### ISSUE TITLE
Page load time.

### ISSUE THREAD

**Issue by grafxflow** [leeovery/wordpress-to-laravel#6]
This is more a query rather than issue.

Does this allow page load speed increase with the use of Laravel for the frontend. (i.e. you can developer better cache with Laravel's built in caching).

**Comment by leeovery** [comment]
Hey,

Thanks for dropping by. This will definitely help with page load time. WP can be extremely slow on a busy blog without serious optimisation. With this approach you can use all the benefits of Laravel caching etc, and make the pages load a lot lighter too.

I use it myself and much prefer the extra control I get.

Cheers
Lee

**Comment by grafxflow** [comment]
Hi leeovery.

The main issue I have relates to the medley of WP plugins installed on the WP site that needs migrating... which is no shock.

I have to measure up the pros and cons of what limitations I would have. What would be lost.

i.e. Shortcodes used in content etc.

**Comment by leeovery** [comment]
Yea that's deffo something to consider. I still use the WP backend so any plugins relating to that can still be used. But obviously anything relating to the front end can't be. But in most cases for a simple blog they are mostly unnecessary. 

Like you say. Pros and cons!
