### ISSUE TITLE
Will not install Laravel 5.5.4

### ISSUE THREAD

**Issue by nomadtechiemike** [leeovery/wordpress-to-laravel#9]
Just tried to run on a fresh install but get requirements could not be resolved to an installable set of packages

## Detailed description

This is my terminal output 

$ composer require leeovery/wordpress-to-laravel
Using version ^1.2 for leeovery/wordpress-to-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.5.4
    - Conclusion: don't install laravel/framework v5.5.4
    - leeovery/wordpress-to-laravel v1.2.0 requires illuminate/events 5.3.*|5.4.* -> satisfiable by illuminate/events[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - leeovery/wordpress-to-laravel v1.2.1 requires illuminate/events 5.3.*|5.4.* -> satisfiable by illuminate/events[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - leeovery/wordpress-to-laravel v1.2.2 requires illuminate/events 5.3.*|5.4.* -> satisfiable by illuminate/events[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - leeovery/wordpress-to-laravel v1.2.3 requires illuminate/events 5.3.*|5.4.* -> satisfiable by illuminate/events[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/events v5.3.0|don't install laravel/framework v5.5.4
    - don't install illuminate/events v5.3.16|don't install laravel/framework v5.5.4
    - don't install illuminate/events v5.3.23|don't install laravel/framework v5.5.4
    - don't install illuminate/events v5.3.4|don't install laravel/framework v5.5.4
    - don't install illuminate/events v5.4.0|don't install laravel/framework v5.5.4
    - don't install illuminate/events v5.4.13|don't install laravel/framework v5.5.4
    - don't install illuminate/events v5.4.17|don't install laravel/framework v5.5.4
    - don't install illuminate/events v5.4.19|don't install laravel/framework v5.5.4
    - don't install illuminate/events v5.4.27|don't install laravel/framework v5.5.4
    - don't install illuminate/events v5.4.36|don't install laravel/framework v5.5.4
    - don't install illuminate/events v5.4.9|don't install laravel/framework v5.5.4
    - Installation request for laravel/framework (locked at v5.5.4, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.4].
    - Installation request for leeovery/wordpress-to-laravel ^1.2 -> satisfiable by leeovery/wordpress-to-laravel[v1.2.0, v1.2.1, v1.2.2, v1.2.3].

Installation failed, reverting ./composer.json to its original content.

## Your environment
XAMPP 
PHP 7.1.9
Laravel 5.5.4

**Comment by coryrose1** [comment]
Same issue

Using version ^1.2 for leeovery/wordpress-to-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.5.28
    - Conclusion: don't install laravel/framework v5.5.28
    - leeovery/wordpress-to-laravel v1.2.0 requires illuminate/events 5.3.*|5.4.* -> satisfiable by illuminate/events[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - leeovery/wordpress-to-laravel v1.2.1 requires illuminate/events 5.3.*|5.4.* -> satisfiable by illuminate/events[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - leeovery/wordpress-to-laravel v1.2.2 requires illuminate/events 5.3.*|5.4.* -> satisfiable by illuminate/events[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - leeovery/wordpress-to-laravel v1.2.3 requires illuminate/events 5.3.*|5.4.* -> satisfiable by illuminate/events[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/events v5.3.0|don't install laravel/framework v5.5.28
    - don't install illuminate/events v5.3.16|don't install laravel/framework v5.5.28
    - don't install illuminate/events v5.3.23|don't install laravel/framework v5.5.28
    - don't install illuminate/events v5.3.4|don't install laravel/framework v5.5.28
    - don't install illuminate/events v5.4.0|don't install laravel/framework v5.5.28
    - don't install illuminate/events v5.4.13|don't install laravel/framework v5.5.28
    - don't install illuminate/events v5.4.17|don't install laravel/framework v5.5.28
    - don't install illuminate/events v5.4.19|don't install laravel/framework v5.5.28
    - don't install illuminate/events v5.4.27|don't install laravel/framework v5.5.28
    - don't install illuminate/events v5.4.36|don't install laravel/framework v5.5.28
    - don't install illuminate/events v5.4.9|don't install laravel/framework v5.5.28
    - Installation request for laravel/framework (locked at v5.5.28, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.28].
    - Installation request for leeovery/wordpress-to-laravel ^1.2 -> satisfiable by leeovery/wordpress-to-laravel[v1.2.0, v1.2.1, v1.2.2, v1.2.3].

**Comment by leeovery** [comment]
I’ll get this sorted ASAP. Sorry. Been extremely busy. Feel free to push a fix for commit.

**Comment by vesper8** [comment]
this commit makes it compatible with 5.6, 5.7 and 5.8

https://github.com/vesper8/wordpress-to-laravel/commit/513c4f2629a0854ddfec7b0636ce25ee92875eae

adding 5.5 would be extremely straightforward if you look at the code modifications I made
